name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.12'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.13'
      - name: Clone
        uses: actions/checkout@v2
        with:
          ref: '04afd9d1e2399d61978fdeeab7e7ac8ff9057a93'
      - name: Build
        run: |
          TAGS="bindata" make build
      - name: Move artifact
        shell: bash
        run: |
          mkdir artifact
          mv gitea artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gitea-${{ matrix.os }}
          path: ./artifact/
